// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC3AYDF2lMXTsXH9RM3bGIF3ZV_rzICQM',
    appId: '1:223248819045:web:9697c1b9133d476105778c',
    messagingSenderId: '223248819045',
    projectId: 'songs-app-ce882',
    authDomain: 'songs-app-ce882.firebaseapp.com',
    databaseURL: 'https://songs-app-ce882-default-rtdb.firebaseio.com',
    storageBucket: 'songs-app-ce882.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn3ETxEZQg3nMBrKDdvfAmoNtGAOLBtAg',
    appId: '1:223248819045:android:aa09e58292628ec405778c',
    messagingSenderId: '223248819045',
    projectId: 'songs-app-ce882',
    databaseURL: 'https://songs-app-ce882-default-rtdb.firebaseio.com',
    storageBucket: 'songs-app-ce882.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0-AmPF4A4B44iGL2SnrQu5QuAsR6macY',
    appId: '1:223248819045:ios:8421894de195eb1205778c',
    messagingSenderId: '223248819045',
    projectId: 'songs-app-ce882',
    databaseURL: 'https://songs-app-ce882-default-rtdb.firebaseio.com',
    storageBucket: 'songs-app-ce882.appspot.com',
    iosClientId: '223248819045-242rmrvs5rjdhemimgik5ef39n2f40s1.apps.googleusercontent.com',
    iosBundleId: 'com.example.songsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0-AmPF4A4B44iGL2SnrQu5QuAsR6macY',
    appId: '1:223248819045:ios:8ab9d9361a319e5b05778c',
    messagingSenderId: '223248819045',
    projectId: 'songs-app-ce882',
    databaseURL: 'https://songs-app-ce882-default-rtdb.firebaseio.com',
    storageBucket: 'songs-app-ce882.appspot.com',
    iosClientId: '223248819045-qt9k12ck7c6v7raemeinurhqhjbhbvov.apps.googleusercontent.com',
    iosBundleId: 'com.example.songsApp.RunnerTests',
  );
}
